vscode/resources/script.js, vscode/src/extension.ts, vscode/src/simulator.ts
The origin for all messages is just "null" for whatever reason. Fixing it by adding a property to indicate the message source.
=> Fixing message routing for sim frame

simloader/loader.ts
Passing simulator search arguments to simulator frame.
=> pass query arguments through loader

packages/makecode-core/src/commands.ts
Support adding built in extensions via add dependency. Fix https://github.com/microsoft/pxt-mkc/issues/53, with https://github.com/microsoft/pxt-mkc/issues/51 partly for builtins / doesn't do a gh search for repos but can add that
=> feat: addDependency supporting builtin dependencies 

packages/makecode-browser/src/languageService.ts, packages/makecode-core/src/commands.ts, packages/makecode-core/src/downloader.ts, packages/makecode-core/src/host.ts, packages/makecode-core/src/mkc.ts, packages/makecode-node/src/languageService.ts
Fetch and save target config and expose to users. Since this is not directly tied to releases / is live I made it also update when we have checked for updates & determined we don't need to pull the full target.
=> feat: command to get target config

packages/makecode-core/src/downloader.ts
I had added this line in https://github.com/microsoft/pxt-mkc/pull/93 as it felt wrong, but it ends up slowing down sim load as that goes through with a 'force update' path. I renamed the parameter to feel a bit better when we still send back cached info when available
=> fix: make it so updating sim doesn't force redownload

packages/makecode-core/simloader/index.html, packages/makecode-core/simloader/loader.ts
Add a stop-sim message listener, and gray out sim when it has been explicit stopped.
=> fix: grayscale sim when stopped to match webapp

packages/makecode-browser/package.json, packages/makecode-node/package.json
fix https://github.com/microsoft/pxt-mkc/issues/97
the build over there just npm i's makecode(-node), and since the core dep is out of date that resulted in a bad build with nothing built https://www.npmjs.com/package/makecode-core/v/0.0.1
=> fix npm i makecode / makecode-browser

packages/makecode-browser/src/types.d.ts, packages/makecode-node/src/bump.ts
https://github.com/microsoft/pxt-mkc/pull/98 didn't run semantic release for these two, I can't tell immediately if it was because it only changed package.json or if it was because because I prefixed it with `fix blah` instead of `fix: blah`. But I think this should release those changes so microcode works again?
=> fix: change ws to release package bump

packages/makecode-browser/tsconfig.json, packages/makecode-browser/worker/tsconfig.json, packages/makecode-core/simloader/tsconfig.json, packages/makecode-core/src/commands.ts, packages/makecode-core/src/service.ts, packages/makecode-core/tsconfig.json, packages/makecode-node/tsconfig.json
...and also sneakily change the build target to ES2017 so that we the compiled JS uses native async/await instead of converting it
The path is needed for https://github.com/microsoft/pxt-vscode-web/issues/51
=> feat: add binary path to compile result

packages/makecode-core/src/loader.ts
arcade has released relatively recently and is effectively up to date across pxt/pxt-common-packages/pxt-arcade, so good time to pin down this default value
part of https://github.com/microsoft/vscode-makecode/issues/81, there's another ref over in that repo
=> fix: point at arcade live site by default, not beta

packages/makecode-browser/src/languageService.ts, packages/makecode-core/src/commands.ts, packages/makecode-core/src/host.ts, packages/makecode-core/src/mkc.ts, packages/makecode-core/src/service.ts
Right now we're spinning up a new worker on any request that needs a language service. This only takes ~50ms to spin up, but we're also leaving the old one around, increasing memory usage by ~5-10mb per compile
fix https://github.com/microsoft/vscode-makecode/issues/78
(and to confirm, this shouldn't have affected makecode-node at all as that spins up a new node process whenever you call into it from cli, correct?)
=> fix: memory leak in makecode-browser

packages/makecode-core/src/commands.ts
hide mkc.json in the file explorer as default (in vscode extension only), and add `.vscode/extensions.json` to match default project from https://github.com/microsoft/pxt/pull/9375/files (in case they e.g. upload to github for others to use)
=> fix: hide mkc.json for vscode extension, suggest vscode extension

packages/makecode-browser/src/languageService.ts, packages/makecode-core/src/commands.ts, packages/makecode-core/src/host.ts, packages/makecode-core/src/mkc.ts, packages/makecode-core/src/service.ts, packages/makecode-node/src/cli.ts, packages/makecode-node/src/languageService.ts
Create `buildSimJsInfo` function to add `BuiltSimJsInfo` information to the compiled JavaScript result.
=> feat: expose function to build sim JS info

package.json
The semantic-release build step is currently broken. Specifically, while running the semantic-release-monrepo plugin's `analyzeCommits` step. Try pinning the major version to 21.
=> fix: Downgrade to semantic release 21

scripts/release.js
Everything works now, but the publish workflow fails when run on an invalid commit. It shouldn't fail, it should just do nothing
=> Don't fail on invalid runs of publish workflow

packages/makecode-core/src/share.ts
the share command currently always outputs share links in the form `www.makecode.com/_xxxxxxxx` which *works*, but doesn't match what our editors return (e.g. `arcade.makecode.com/_xxxxxxxx`). the generic `makecode.com/` links don't work with the import project button on the homescreen or in the extensions dialog.
this pr grabs the editor URL from the project and uses that as the root for the share link instead.
=> use editor url for share links

package-lock.json, packages/makecode-core/package.json, packages/makecode-core/simloader/loader.ts, packages/makecode-core/src/commands.ts
this adds a command to pxt-mkc for getting the html file of the sim, which mkc already downloads when it downloads the editor. to simplify serving the file, the code also inlines all of the javascript and css into one monolithic html file. for the inlining part i added a dependency to [\@xmldom/xmldom](https://www.npmjs.com/package/@xmldom/xmldom) since domparser is not available in node or in a webworker context (which is where the vscode extension runs).
this pr also adds a new optional srcDoc parameter to the fetch-js message which gets sent to the simloader page that is hosted by `makecode serve` and the vscode extension. when that parameter is specified, the loader will use it to [populate the sim iframe](https://developer.mozilla.org/en-US/docs/Web/API/HTMLIFrameElement/srcdoc) …
=> Add command for getting a single sim html file and loading it in iframe

packages/makecode-core/src/commands.ts, packages/makecode-core/src/downloader.ts
this pr:
* fixes the parsing of the webconfig from index.html which was using a regex that got broken by the recent OCV changes in the backend
* adds the /---asseteditor endpoint to the locally cached files so that we can serve it locally in the vscode extension
* improves the HTML inlining code from my last PR
the reason for the changes to the HTML inlining code is that the asseteditor references pxtapp.js which includes a bunch of open and close `<script>` tags that were confusing chrome's HTML parser. now all scripts are base64 encoded and inlined into the HTML file where a tiny piece of JS decodes them and adds them to the page after the DOM is parsed. the downside of this approach is that the file we generate is now much, much bigger than before, but i can't think of any alternatives …
=> add asseteditor to mkc cache and fix webconfig parsing

packages/makecode-core/src/commands.ts, packages/makecode-core/src/downloader.ts, packages/makecode-core/src/host.ts, packages/makecode-node/src/nodeHost.ts
this PR improves the page expanding for asseteditor.html so that it also inlines all of the PNG icons for the music editor. fetching all of those icons involves making a lot of requests, so i also made it so that the expanded file is now stored in the cache along with the expanded sim.html so that we don't re-calculate them every time you click on a new asset. finally, i also removed the btoa encoding on the inlined scripts because it turns out the encodeURIComponent is already enough.
@aznhassan i don't know if your script compilation implements the host, but FYI this adds one additional API to the host interface so if you take this mkc update you'll need to implement it (or include a dummy implementation since it won't actually get called in your scenario). i'll also need to update the …
=> improve page expanding and cache results in mkc cache

packages/makecode-core/src/downloader.ts
fixes https://github.com/microsoft/pxt-mkc/issues/134
the micro:bit webconfig has no ocv data so it ends up looking like this:
```
"ocv": {}
```
which broke my parsing. fix is simply switching from and else-if to an if
=> fix parsing of micro:bit webconfig

packages/makecode-core/src/commands.ts
this is needed for the simx support in the simulator of the vscode extension; we need to fetch the simulator url from the webconfig
=> add command to fetch webconfig

package-lock.json, packages/makecode-core/package.json
__Do not edit the PR title.__
It was automatically generated by `node ./scripts/release.js bump` and must follow a specific pattern.
GitHub workflows rely on it to trigger version tagging and publishing to npm.
=> [release] bump version to makecode-core-v1.7.5

package-lock.json, packages/makecode-core/package.json
__Do not edit the PR title.__
It was automatically generated by `node ./scripts/release.js bump` and must follow a specific pattern.
GitHub workflows rely on it to trigger version tagging and publishing to npm.
=> [release] bump version to makecode-core-v1.7.6

package-lock.json, packages/makecode-core/package.json
__Do not edit the PR title.__
It was automatically generated by `node ./scripts/release.js bump` and must follow a specific pattern.
GitHub workflows rely on it to trigger version tagging and publishing to npm.
=> [release] bump version to makecode-core-v1.7.7

.github/workflows/build.yml, scripts/release.js
fix publish script. we can no longer use the tag environment variable because that isn't what triggers the workflow
=> parse commit message instead of tag

package-lock.json, packages/makecode-core/package.json
__Do not edit the PR title.__
It was automatically generated by `node ./scripts/release.js bump` and must follow a specific pattern.
GitHub workflows rely on it to trigger version tagging and publishing to npm.
=> [release] bump version to makecode-core-v1.7.8
